#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TRUE 1
#define FALSE 0

#define GRID_SIZE_X 8 
#define GRID_SIZE_Y 8 
#define MONTH_DAYS 30
#define YEARS_TO_SIMULATE 100

#define INITIAL_RABBITS 10
#define INITIAL_FOXES 5
#define INITIAL_VEGETATION 0.5

#define LOW_VEGETATION 0.2
#define MID_VEGETATION 0.5
#define HIGH_VEGETATION 0.8

#define LOW_RABBITS_T1 2
#define MID_LOW_RABBITS_T1 201
#define MID_HIGH_RABBITS_T1 701
#define HIGH_RABBITS_T1 5001

#define LOW_RABBITS_FOX 3
#define MID_RABBITS_FOX 10
#define HIGH_RABBITS_FOX 40

#define LOW_FOXES 2
#define MID_LOW_FOXES 11
#define MID_HIGH_FOXES 51
#define HIGH_FOXES 100

#define LOW_VEGETATION_LEVEL 0.1
#define MID_LOW_VEGETATION_LEVEL 0.15
#define MID_HIGH_VEGETATION_LEVEL 0.25
#define HIGH_VEGETATION_LEVEL 0.35

#endif